training:
  iterations: 200000
  eval_steps: 500
  eval_examples: 1000
  lr: 0.001
  early_stopping: 15
  lr_plateau: 10
  optimizer: "adam"
dataset:
  name: "SatFlowDataset"
  batch_size: 8
  num_timesteps: 6
  skip_timesteps: 2
  forecast_times: 12
  output_shape: 128
  target_type: "cloudmask"
  num_crops: 10
  use_topo: True
  use_latlon: True
  use_time: True
  time_aux: False
  use_mask: True
  use_image: False
  sources:
    train: "/run/media/jacob/HDD/satflow-flow-{00001..00105..2}.tar"
    test: "/run/media/jacob/HDD/satflow-flow-{00002..00106..4}.tar"
  bands: ["HRV","IR016","IR039","IR087","IR097","IR108","IR120","IR134","VIS006","VIS008","WV062","WV073",]
  transforms: {}
test: {}
model:
  name: "LitUnet"
  in_channels: 32
  input_size: 128
  channels: 12
