# @package _group_
_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 1

min_epochs: 0
max_epochs: 99999
min_steps: 20000
max_steps: 2000000
val_check_interval: 2000
limit_train_batches: 20000
limit_val_batches: 1000

terminate_on_nan: True
auto_lr_find: True
auto_scale_batch_size: False

weights_summary: null
progress_bar_refresh_rate: 10
# resume_from_checkpoint: null
