_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 1

min_epochs: 1
max_epochs: 200

terminate_on_nan: False
auto_lr_find: False
auto_scale_batch_size: False
accumulate_grad_batches: 1
precision: 32
# stochastic_weight_avg: True
fast_dev_run: False

weights_summary: null
progress_bar_refresh_rate: 1
# resume_from_checkpoint: "/home/jacob/Development/satflow/satflow/logs/runs/2021-08-09/09-13-09/checkpoints/epoch=09.ckpt"
