# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python run.py -m hparams_search=mnist_optuna experiment=example_simple
# python run.py -m hparams_search=mnist_optuna experiment=example_simple hydra.sweeper.n_trials=30
# python run.py -m hparams_search=mnist_optuna experiment=example_simple logger=wandb

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
optimized_metric: "val/loss"

hydra:
  # here we define Optuna hyperparameter search
  # it optimizes for value returned from function with @hydra.main decorator
  # learn more here: https://hydra.cc/docs/next/plugins/optuna_sweeper
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: "sqlite:///skillful_nowcasting.db"
    study_name: skillful_nowcasting
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: minimize

    # number of experiments that will be executed
    n_trials: 20

    # choose Optuna hyperparameter sampler
    # learn more here: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 12345
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 10
      n_ei_candidates: 24
      multivariate: false
      warn_independent_sampling: true

    # define range of hyperparameters
    search_space:
      datamodule.batch_size:
        type: categorical
        choices: [2]
      datamodule.config.num_timesteps:
        type: categorical
        choices: [1, 3, 6, 9]
      datamodule.config.skip_timesteps:
        type: categorical
        choices: [1, 2, 3]
      model.grid_lambda:
        type: float
        low: 0.1
        high: 200.0
      model.num_samples:
        type: categorical
        choices: [1, 3, 5, 7]
      model.conv_type:
        type: categorical
        choices: ["standard", "coord"]
      model.disc_lr:
        type: float
        low: 0.00002
        high: 0.02
      model.gen_lr:
        type: float
        low: 0.000005
        high: 0.005
