# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python run.py -m hparams_search=mnist_optuna experiment=example_simple
# python run.py -m hparams_search=mnist_optuna experiment=example_simple hydra.sweeper.n_trials=30
# python run.py -m hparams_search=mnist_optuna experiment=example_simple logger=wandb

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
optimized_metric: "val/loss"

hydra:
  # here we define Optuna hyperparameter search
  # it optimizes for value returned from function with @hydra.main decorator
  # learn more here: https://hydra.cc/docs/next/plugins/optuna_sweeper
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: "sqlite:///perceiver.db"
    study_name: perceiver
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: minimize

    # number of experiments that will be executed
    n_trials: 50

    # choose Optuna hyperparameter sampler
    # learn more here: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 12345
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 10
      n_ei_candidates: 24
      multivariate: false
      warn_independent_sampling: true

    # define range of hyperparameters
    search_space:
      datamodule.batch_size:
        type: categorical
        choices: [2]
      datamodule.config.num_timesteps:
        type: categorical
        choices: [1, 3, 6, 9]
      datamodule.config.skip_timesteps:
        type: categorical
        choices: [1, 2, 3]
      model.lr:
        type: float
        low: 0.0001
        high: 0.2
      model.depth:
        type: categorical
        choices: [6, 4, 8, 2]
      model.cross_heads:
        type: categorical
        choices: [1, 2]
      model.latent_heads:
        type: categorical
        choices: [2, 4, 8, 16]
      model.cross_dim_heads:
        type: categorical
        choices: [1, 2, 4, 8]
      model.self_per_cross_attention:
        type: categorical
        choices: [1, 2, 4, 8]
      model.num_latents:
        type: categorical
        choices: [64, 128, 256, 512, 1024]
      model.latent_dim:
        type: categorical
        choices: [64, 128, 256, 512, 1024]
      model.max_frequency:
        type: float
        low: 2.0
        high: 32.0
      model.weight_tie_layers:
        type: categorical
        choices: [false, true]
      model.preprocessor_type:
        type: categorical
        choices: ["metnet"]
