# @package _group_
_target_: satflow.models.pix2pix.Pix2Pix
forecast_steps: 48
input_channels: 12
lr: 0.0002
beta1: 0.5
beta2: 0.999
num_filters: 64
generator_model: "unet_128"
norm: "batch"
use_dropout: false
discriminator_model: "basic"
discriminator_layers: 0
loss: "vanilla"
scheduler: "cosine"
lr_epochs: 10
