_target_: nowcasting_dataloader.datamodules.SatFlowDataModule

temp_path: "."
n_train_data: 24900
n_val_data: 1000
cloud: "local"
num_workers: 8
pin_memory: True
configuration_filename: "nowcasting_dataset/nowcasting_dataset/config/on_premises.yaml"
history_minutes: 30
forecast_minutes: 120

