_target_: satflow.data.datamodules.SatFlowDataModule

batch_size: 8
data_dir: ${data_dir} # data_dir is specified in config.yaml
shuffle: 0
sources:
  train: "pipe:aws s3 cp s3://solar-pv-nowcasting-data/webdataset/satflow-train-{00000..00214}.tar -"
  val: "pipe:aws s3 cp s3://solar-pv-nowcasting-data/webdataset/satflow-val-{00000..00060}.tar -"
  test: "pipe:aws s3 cp s3://solar-pv-nowcasting-data/webdataset/satflow-test-{00000..00057}.tar -"
num_workers: 12
pin_memory: True
prefetch_factor: 4
config:
  visualize: False
  num_timesteps: 3
  skip_timesteps: 1
  forecast_times: 24
  output_shape: 128
  output_target: 32
  target_type: "cloudmask"
  num_crops: 5
  num_times: 4
  use_topo: True
  use_latlon: True
  use_time: False
  time_aux: False
  use_mask: False
  use_image: True
  time_as_channels: False
  add_pixel_coords: False
  add_polar_coords: False
  bands:
    [
      "HRV",
      "IR016",
      "IR039",
      "IR087",
      "IR097",
      "IR108",
      "IR120",
      "IR134",
      "VIS006",
      "VIS008",
      "WV062",
      "WV073",
    ]
  transforms: {}
