_target_: nowcasting_dataloader.datamodules.SatFlowDataModule

temp_path: "."
cloud: "aws"
num_workers: 6
pin_memory: True
configuration: "s3://solar-pv-nowcasting-data/prepared_ML_training_data/v16/configuration.yaml"
history_minutes: 30
forecast_minutes: 120
normalize: True
add_position_encoding: True
add_satellite_target: False
add_hrv_satellite_target: False
data_sources_names: ["gsp", "pv", "hrvsatellite", "nwp"]