# @package _group_
name: "SatFlowDataset"
batch_size: 2
num_workers: 4
num_timesteps: 3
skip_timesteps: 1
forecast_times: 12
output_shape: 128
target_type: "cloudmask"
num_crops: 10
use_topo: True
use_latlon: True
use_time: False
time_aux: False
use_mask: True
use_image: False
pin_memory: True
sources:
  train: "/run/media/bieker/data/EUMETSAT/2020/satflow-flow-36-{00001..00105..2}.tar"
  val: "/run/media/bieker/data/EUMETSAT/2020/satflow-flow-36-{00002..00105..4}.tar"
  test: "/run/media/bieker/data/EUMETSAT/2021/satflow-flow-36-{000106..00150}.tar"
bands:
  [
    "HRV",
    "IR016",
    "IR039",
    "IR087",
    "IR097",
    "IR108",
    "IR120",
    "IR134",
    "VIS006",
    "VIS008",
    "WV062",
    "WV073",
  ]
transforms: {}
