# @package _group_
name: "SatFlowDataset"
batch_size: 2
num_workers: 4
num_timesteps: 3
skip_timesteps: 1
forecast_times: 6
output_shape: 128
target_type: "cloudmask"
num_crops: 10
use_topo: True
use_latlon: True
use_time: False
time_aux: False
use_mask: True
use_image: True
pin_memory: True
sources:
  train: "/run/media/jacob/HDD/chunked/satflow-flow-12-00031.tar"
  val: "/run/media/jacob/HDD/chunked/satflow-flow-12-00045.tar"
  test: "/run/media/jacob/HDD/chunked/satflow-flow-12-00131.tar"
bands:
  [
      "HRV",
      "IR016",
      "IR039",
      "IR087",
      "IR097",
      "IR108",
      "IR120",
      "IR134",
      "VIS006",
      "VIS008",
      "WV062",
      "WV073",
  ]
transforms: {}
